language: java
jdk:
  - oraclejdk8
services:
  - redis-server
before_install:
  - chmod +x gradlew
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c227ba0fb2db2795a73c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

